# Generated by Django 4.2.8 on 2023-12-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_products', to='bills.bill')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_products', to='products.product')),
            ],
        ),
    ]
